-- Festival Passport account ownership and safe first-device migration.
-- Run once in the Supabase SQL editor. Existing travel data is not deleted.

create table if not exists public.festival_passport_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.festival_passport_device_backups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id uuid not null,
  source text not null default 'first_account_migration',
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists festival_passport_device_backups_user_created_idx
  on public.festival_passport_device_backups(user_id, created_at desc);

alter table public.festival_passport_profiles enable row level security;
alter table public.festival_passport_device_backups enable row level security;
alter table public.travel_companion_data enable row level security;

drop policy if exists "account owners manage profile" on public.festival_passport_profiles;
create policy "account owners manage profile"
  on public.festival_passport_profiles for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists "account owners create device backups" on public.festival_passport_device_backups;
create policy "account owners create device backups"
  on public.festival_passport_device_backups for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and coalesce((select auth.jwt()->>'is_anonymous')::boolean, false) is false
  );

drop policy if exists "account owners read device backups" on public.festival_passport_device_backups;
create policy "account owners read device backups"
  on public.festival_passport_device_backups for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists "account owners manage travel data" on public.travel_companion_data;
create policy "account owners manage travel data"
  on public.travel_companion_data for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists "permanent accounts only travel data" on public.travel_companion_data;
create policy "permanent accounts only travel data"
  on public.travel_companion_data as restrictive for all to authenticated
  using (
    user_id = (select auth.uid())
    and coalesce((select auth.jwt()->>'is_anonymous')::boolean, false) is false
  )
  with check (
    user_id = (select auth.uid())
    and coalesce((select auth.jwt()->>'is_anonymous')::boolean, false) is false
  );

grant select, insert, update on public.festival_passport_profiles to authenticated;
grant select, insert on public.festival_passport_device_backups to authenticated;

create or replace function public.handle_festival_passport_account()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(new.is_anonymous, false) is false then
    insert into public.festival_passport_profiles(user_id, display_name, avatar_url)
    values (
      new.id,
      coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name'),
      coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture')
    )
    on conflict (user_id) do update
      set display_name = coalesce(excluded.display_name, festival_passport_profiles.display_name),
          avatar_url = coalesce(excluded.avatar_url, festival_passport_profiles.avatar_url),
          updated_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists on_festival_passport_auth_user on auth.users;
create trigger on_festival_passport_auth_user
  after insert or update of raw_user_meta_data, is_anonymous on auth.users
  for each row execute procedure public.handle_festival_passport_account();

insert into public.festival_passport_profiles(user_id, display_name, avatar_url)
select
  id,
  coalesce(raw_user_meta_data->>'name', raw_user_meta_data->>'full_name'),
  coalesce(raw_user_meta_data->>'avatar_url', raw_user_meta_data->>'picture')
from auth.users
where coalesce(is_anonymous, false) is false
on conflict (user_id) do nothing;
